spring:
  application:
    name: smart-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/smart?characterEncoding=utf8
    username: root
    password: 12345678
server:
  port: 8082

#实体扫描，仅使用mapper.xml才需要这些配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*.xml
  typeAliasesPackage: com.smart.**.entity

